### ISSUE TITLE
Default Windows Voices

### ISSUE THREAD

**Issue by FernandoNotedigo** [rkusa/DATIS#81] opened 2021-01-16 17:26 UTC
Hi Everyone!
First of all I'd like to thank you for this spectacular tool. It works fantastically.

I am trying to change the voices (using Windows voices) but i can´t make it work in my stand alone server.

In the configuration (options.lua) I selected ["defaultVoice"] = "WIN:Hazel" (Hazel is the voice I want to use).  This doesn't seem to work.

I've also changed the default voice to Hazel in Windows setting but is not working as well.

The standard voice it uses is different (male voice), no matter what I change. It works ok but I don't know how to do the change.

By the way, I am setting up the ATIS station inside the Mission Situation using something like: "ATIS Kish Intl 250.700".

Thanks!

**Comment by rkusa** [comment] 2021-01-18 15:51
Hi, I am glad you like the tool! Could you try again using the voice and then attach your server's `DCS.openbeta\Logs\DATIS.log` file here? It should contain an error if it was unable to use the voice and a list of available voices. This should help us find the cause of your issue.

**Comment by FernandoNotedigo** [comment] 2021-01-18 16:53
Hi! Thanks for your answer.

Here is the Log. It's weird because I've got no error message. The voice, however, is male and not female. 

[DATIS.log](https://github.com/rkusa/DATIS/files/5831528/DATIS.log)

**Comment by FernandoNotedigo** [comment] 2021-01-18 16:55
Here is the config from options.lua

`        ["DATIS"] = 
        {
            ["debugLoggingEnabled"] = false,
            ["awsAccessKey"] = "Your AWS access key",
            ["awsPrivateKey"] = "Your AWS private key",
            ["srsPort"] = "5002",
            ["awsRegion"] = "eu-central-1",
            ["gcloudAccessKey"] = "Your Google Cloud access key",
            ["defaultVoice"] = "WIN:Hazel",
        }, -- end of ["DATIS"]`

**Comment by rkusa** [comment] 2021-01-18 17:03
Thanks for the logs. No error message is unexpected here. I'll look into it in more detail and get back to you once I know more

**Comment by FernandoNotedigo** [comment] 2021-01-18 17:04
> Thanks for the logs. No error message is unexpected here. I'll look into it in more detail and get back to you once I know more

Thanks!

**Comment by rkusa** [comment] 2021-01-19 20:48
Should be fixed in https://github.com/rkusa/DATIS/releases/tag/2.2.0-beta.7
Thanks again for the report!

**Closed by rkusa** 2021-01-19 20:48 UTC

**Comment by FernandoNotedigo** [comment] 2021-01-20 05:46
Thanks a lot. I will try it tomorrow!

**Comment by FernandoNotedigo** [comment] 2021-01-20 05:54
Couldn't wait. It works perfectly. thanks!
