### ISSUE TITLE
target machine actively refused it. (os error 10061)

### ISSUE THREAD

**Issue by VCW3-admin** [rkusa/DATIS#44] opened 2020-05-01 20:34 UTC
Im getting this error with 1.8.0 SRS and DATIS alpha 10
`2020-05-01T13:45:30.129364-05:00 INFO datis - Starting DATIS version 1.0.0-alpha.10 ...
2020-05-01T13:45:30.145077100-05:00 INFO datis::mission - Using SRS Server port: 5014
2020-05-01T13:45:31.592450700-05:00 WARN datis::mission - Invalid default voice `win`: unknown variant `win`, expected one of `en-US-Standard-B`, `en-US-Standard-C`, `en-US-Standard-D`, `en-US-Standard-E`, `en-US-Wavenet-A`, `en-US-Wavenet-B`, `en-US-Wavenet-C`, `en-US-Wavenet-D`, `en-US-Wavenet-E`, `en-US-Wavenet-F`
2020-05-01T13:45:33.924746900-05:00 INFO datis - Resuming ...
2020-05-01T13:45:35.968656-05:00 ERROR datis_core - ATIS Tonopah Test Range Airfield failed: No connection could be made because the target machine actively refused it. (os error 10061)
2020-05-01T13:45:35.968656-05:00 INFO datis_core - Restarting ATIS Tonopah Test Range Airfield in 60 seconds ...
2020-05-01T13:45:35.984278300-05:00 ERROR datis_core - ATIS Creech AFB failed: No connection could be made because the target machine actively refused it. (os error 10061)
2020-05-01T13:45:35.984278300-05:00 INFO datis_core - Restarting ATIS Creech AFB in 60 seconds ...
2020-05-01T13:45:35.984278300-05:00 ERROR datis_core - ATIS Groom Lake AFB failed: No connection could be made because the target machine actively refused it. (os error 10061)
2020-05-01T13:45:35.984278300-05:00 INFO datis_core - Restarting ATIS Groom Lake AFB in 60 seconds ...
2020-05-01T13:45:35.984278300-05:00 ERROR datis_core - ATIS Nellis AFB failed: No connection could be made because the target machine actively refused it. (os error 10061)
2020-05-01T13:45:35.984278300-05:00 INFO datis_core - Restarting ATIS Nellis AFB in 60 seconds ...`

Any suggestions

**Comment by VCW3-admin** [comment] 2020-05-02 04:27
I'm now seeing multiple. 
[DATIS.log](https://github.com/rkusa/DATIS/files/4567077/DATIS.log)
![DATIS Issue 1 8 0 SRS](https://user-images.githubusercontent.com/63507784/80855063-52ca4680-8c03-11ea-92b3-e845d9de5042.png)

**Comment by rkusa** [comment] 2020-05-02 21:06
Thanks for the report 👍. I see some other things in the logs as well. I’ll look into all of them, in the next couple of days and get back to you.

**Comment by VCW3-admin** [comment] 2020-05-02 21:26
rodger that thank you..

**Comment by rkusa** [comment] 2020-05-03 08:05
I've published a new version: https://github.com/rkusa/DATIS/releases/tag/1.0.0-beta.1, which fixes the following to issues I saw in your log:

```
Invalid default voice `win`: unknown variant `win`
failed to get unit position: unit not found
```

However, I was unfortunately unable to reproduce your main issue. Would you mind enabling the debug checkbox in the DATIS settings of DCS SPECIALS menu and upload the resulting logs again?

**Comment by VCW3-admin** [comment] 2020-05-03 14:04
No problem. Let me do that today and I’ll post it as soon as I have something.

**Comment by VCW3-admin** [comment] 2020-05-03 16:39
Good morning 
I attached a copy of the log as you can see with the latest Beta. Far better as as soon as I joined it showed the right number of clients in the session such as myself and the four atis stations for as total of 5 clients. That was consistent with only flying out of Nellis. my next test was to leave exit the DCS server and the SRS server and rejoin. As soon as I did that again it started to show me the double the atis stations plus myself making the total number of clients to 9. as soon as exited the servers the atis stations went down to 6 and stayed at six stations as indicated here in the screen shot. 
![DATIS Issue beta1](https://user-images.githubusercontent.com/63507784/80920012-b0a97c00-8d32-11ea-8668-1d1724ea6c0e.png)


[DATIS.log](https://github.com/rkusa/DATIS/files/4570959/DATIS.log)

**Comment by rkusa** [comment] 2020-05-05 08:51
Thanks for the update! It looks like some stations are sometimes not shut down properly when either the mission is ended or paused. I've released a new version where I didn't see this issue anymore https://github.com/rkusa/DATIS/releases/tag/1.0.0-beta.2, but I wouldn't be surprised if it still happens sometimes - I'll definitely keep an eye on it.

**Comment by rkusa** [comment] 2020-05-21 20:59
Your remaining issue should be fixed with https://github.com/ciribob/DCS-SimpleRadioStandalone/releases/tag/1.8.0.4

**Closed by rkusa** 2020-05-21 20:59 UTC
